<?xml version="1.0" encoding="utf-8"?><Database Name="BildeDatabase" Class="ormMinKunstDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\BildeDatabase.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BildeDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bilde" Member="Bildes">
    <Type Name="Bilde">
      <Column Name="BildeId" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tittel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Bildenavn" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BrukerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KommentarId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Bilde_Kommentar" Member="Kommentars" ThisKey="BildeId" OtherKey="BildeId" Type="Kommentar" />
      <Association Name="Kommentar_Bilde" Member="Kommentar" ThisKey="KommentarId" OtherKey="KommentarId" Type="Kommentar" IsForeignKey="true" />
      <Association Name="Bruker_Bilde" Member="Bruker" ThisKey="BrukerId" OtherKey="BrukerId" Type="Bruker" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kommentar" Member="Kommentars">
    <Type Name="Kommentar">
      <Column Name="KommentarId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tittel" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Innhold" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="BrukerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BildeId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Kommentar_Bilde" Member="Bildes" ThisKey="KommentarId" OtherKey="KommentarId" Type="Bilde" />
      <Association Name="Bilde_Kommentar" Member="Bilde" ThisKey="BildeId" OtherKey="BildeId" Type="Bilde" IsForeignKey="true" />
      <Association Name="Bruker_Kommentar" Member="Bruker" ThisKey="BrukerId" OtherKey="BrukerId" Type="Bruker" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bruker" Member="Brukers">
    <Type Name="Bruker">
      <Column Name="BrukerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Brukernavn" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Passord" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Navn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Profilbilde" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Bruker_Bilde" Member="Bildes" ThisKey="BrukerId" OtherKey="BrukerId" Type="Bilde" />
      <Association Name="Bruker_Kommentar" Member="Kommentars" ThisKey="BrukerId" OtherKey="BrukerId" Type="Kommentar" />
    </Type>
  </Table>
</Database>