#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbRomskipet")]
public partial class ormRomskipetDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertAdministrator(Administrator instance);
  partial void UpdateAdministrator(Administrator instance);
  partial void DeleteAdministrator(Administrator instance);
  partial void InsertProdukt(Produkt instance);
  partial void UpdateProdukt(Produkt instance);
  partial void DeleteProdukt(Produkt instance);
  partial void InsertAktivitetPåmelding(AktivitetPåmelding instance);
  partial void UpdateAktivitetPåmelding(AktivitetPåmelding instance);
  partial void DeleteAktivitetPåmelding(AktivitetPåmelding instance);
  partial void InsertBruker(Bruker instance);
  partial void UpdateBruker(Bruker instance);
  partial void DeleteBruker(Bruker instance);
  partial void InsertForeleser(Foreleser instance);
  partial void UpdateForeleser(Foreleser instance);
  partial void DeleteForeleser(Foreleser instance);
  partial void InsertForeleserPåmelding(ForeleserPåmelding instance);
  partial void UpdateForeleserPåmelding(ForeleserPåmelding instance);
  partial void DeleteForeleserPåmelding(ForeleserPåmelding instance);
  partial void InsertKurs(Kurs instance);
  partial void UpdateKurs(Kurs instance);
  partial void DeleteKurs(Kurs instance);
  partial void InsertKursPåmelding(KursPåmelding instance);
  partial void UpdateKursPåmelding(KursPåmelding instance);
  partial void DeleteKursPåmelding(KursPåmelding instance);
  partial void InsertBilder(Bilder instance);
  partial void UpdateBilder(Bilder instance);
  partial void DeleteBilder(Bilder instance);
  partial void InsertOrdrelinje(Ordrelinje instance);
  partial void UpdateOrdrelinje(Ordrelinje instance);
  partial void DeleteOrdrelinje(Ordrelinje instance);
  partial void InsertNyhet(Nyhet instance);
  partial void UpdateNyhet(Nyhet instance);
  partial void DeleteNyhet(Nyhet instance);
  partial void InsertAktivitet(Aktivitet instance);
  partial void UpdateAktivitet(Aktivitet instance);
  partial void DeleteAktivitet(Aktivitet instance);
  #endregion
	
	public ormRomskipetDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbRomskipetConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ormRomskipetDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ormRomskipetDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ormRomskipetDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ormRomskipetDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Administrator> Administrators
	{
		get
		{
			return this.GetTable<Administrator>();
		}
	}
	
	public System.Data.Linq.Table<Produkt> Produkts
	{
		get
		{
			return this.GetTable<Produkt>();
		}
	}
	
	public System.Data.Linq.Table<AktivitetPåmelding> AktivitetPåmeldings
	{
		get
		{
			return this.GetTable<AktivitetPåmelding>();
		}
	}
	
	public System.Data.Linq.Table<Bruker> Brukers
	{
		get
		{
			return this.GetTable<Bruker>();
		}
	}
	
	public System.Data.Linq.Table<Foreleser> Forelesers
	{
		get
		{
			return this.GetTable<Foreleser>();
		}
	}
	
	public System.Data.Linq.Table<ForeleserPåmelding> ForeleserPåmeldings
	{
		get
		{
			return this.GetTable<ForeleserPåmelding>();
		}
	}
	
	public System.Data.Linq.Table<Kurs> Kurs
	{
		get
		{
			return this.GetTable<Kurs>();
		}
	}
	
	public System.Data.Linq.Table<KursPåmelding> KursPåmeldings
	{
		get
		{
			return this.GetTable<KursPåmelding>();
		}
	}
	
	public System.Data.Linq.Table<Bilder> Bilders
	{
		get
		{
			return this.GetTable<Bilder>();
		}
	}
	
	public System.Data.Linq.Table<Ordrelinje> Ordrelinjes
	{
		get
		{
			return this.GetTable<Ordrelinje>();
		}
	}
	
	public System.Data.Linq.Table<Nyhet> Nyhets
	{
		get
		{
			return this.GetTable<Nyhet>();
		}
	}
	
	public System.Data.Linq.Table<Aktivitet> Aktivitets
	{
		get
		{
			return this.GetTable<Aktivitet>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrator")]
public partial class Administrator : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AdminID;
	
	private string _Brukernavn;
	
	private string _Passord;
	
	private string _Fornavn;
	
	private string _Etternavn;
	
	private int _Mobil;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAdminIDChanging(int value);
    partial void OnAdminIDChanged();
    partial void OnBrukernavnChanging(string value);
    partial void OnBrukernavnChanged();
    partial void OnPassordChanging(string value);
    partial void OnPassordChanged();
    partial void OnFornavnChanging(string value);
    partial void OnFornavnChanged();
    partial void OnEtternavnChanging(string value);
    partial void OnEtternavnChanged();
    partial void OnMobilChanging(int value);
    partial void OnMobilChanged();
    #endregion
	
	public Administrator()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int AdminID
	{
		get
		{
			return this._AdminID;
		}
		set
		{
			if ((this._AdminID != value))
			{
				this.OnAdminIDChanging(value);
				this.SendPropertyChanging();
				this._AdminID = value;
				this.SendPropertyChanged("AdminID");
				this.OnAdminIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brukernavn", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
	public string Brukernavn
	{
		get
		{
			return this._Brukernavn;
		}
		set
		{
			if ((this._Brukernavn != value))
			{
				this.OnBrukernavnChanging(value);
				this.SendPropertyChanging();
				this._Brukernavn = value;
				this.SendPropertyChanged("Brukernavn");
				this.OnBrukernavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passord", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Passord
	{
		get
		{
			return this._Passord;
		}
		set
		{
			if ((this._Passord != value))
			{
				this.OnPassordChanging(value);
				this.SendPropertyChanging();
				this._Passord = value;
				this.SendPropertyChanged("Passord");
				this.OnPassordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fornavn", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string Fornavn
	{
		get
		{
			return this._Fornavn;
		}
		set
		{
			if ((this._Fornavn != value))
			{
				this.OnFornavnChanging(value);
				this.SendPropertyChanging();
				this._Fornavn = value;
				this.SendPropertyChanged("Fornavn");
				this.OnFornavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etternavn", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string Etternavn
	{
		get
		{
			return this._Etternavn;
		}
		set
		{
			if ((this._Etternavn != value))
			{
				this.OnEtternavnChanging(value);
				this.SendPropertyChanging();
				this._Etternavn = value;
				this.SendPropertyChanged("Etternavn");
				this.OnEtternavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobil", DbType="Int NOT NULL")]
	public int Mobil
	{
		get
		{
			return this._Mobil;
		}
		set
		{
			if ((this._Mobil != value))
			{
				this.OnMobilChanging(value);
				this.SendPropertyChanging();
				this._Mobil = value;
				this.SendPropertyChanged("Mobil");
				this.OnMobilChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produkt")]
public partial class Produkt : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ProduktID;
	
	private string _ProduktNavn;
	
	private decimal _Pris;
	
	private string _Beskrivelse;
	
	private string _Bilde;
	
	private EntitySet<Ordrelinje> _Ordrelinjes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProduktIDChanging(int value);
    partial void OnProduktIDChanged();
    partial void OnProduktNavnChanging(string value);
    partial void OnProduktNavnChanged();
    partial void OnPrisChanging(decimal value);
    partial void OnPrisChanged();
    partial void OnBeskrivelseChanging(string value);
    partial void OnBeskrivelseChanged();
    partial void OnBildeChanging(string value);
    partial void OnBildeChanged();
    #endregion
	
	public Produkt()
	{
		this._Ordrelinjes = new EntitySet<Ordrelinje>(new Action<Ordrelinje>(this.attach_Ordrelinjes), new Action<Ordrelinje>(this.detach_Ordrelinjes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ProduktID
	{
		get
		{
			return this._ProduktID;
		}
		set
		{
			if ((this._ProduktID != value))
			{
				this.OnProduktIDChanging(value);
				this.SendPropertyChanging();
				this._ProduktID = value;
				this.SendPropertyChanged("ProduktID");
				this.OnProduktIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktNavn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string ProduktNavn
	{
		get
		{
			return this._ProduktNavn;
		}
		set
		{
			if ((this._ProduktNavn != value))
			{
				this.OnProduktNavnChanging(value);
				this.SendPropertyChanging();
				this._ProduktNavn = value;
				this.SendPropertyChanged("ProduktNavn");
				this.OnProduktNavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pris", DbType="Decimal(18,0) NOT NULL")]
	public decimal Pris
	{
		get
		{
			return this._Pris;
		}
		set
		{
			if ((this._Pris != value))
			{
				this.OnPrisChanging(value);
				this.SendPropertyChanging();
				this._Pris = value;
				this.SendPropertyChanged("Pris");
				this.OnPrisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beskrivelse", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Beskrivelse
	{
		get
		{
			return this._Beskrivelse;
		}
		set
		{
			if ((this._Beskrivelse != value))
			{
				this.OnBeskrivelseChanging(value);
				this.SendPropertyChanging();
				this._Beskrivelse = value;
				this.SendPropertyChanged("Beskrivelse");
				this.OnBeskrivelseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bilde", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
	public string Bilde
	{
		get
		{
			return this._Bilde;
		}
		set
		{
			if ((this._Bilde != value))
			{
				this.OnBildeChanging(value);
				this.SendPropertyChanging();
				this._Bilde = value;
				this.SendPropertyChanged("Bilde");
				this.OnBildeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produkt_Ordrelinje", Storage="_Ordrelinjes", ThisKey="ProduktID", OtherKey="ProduktID")]
	public EntitySet<Ordrelinje> Ordrelinjes
	{
		get
		{
			return this._Ordrelinjes;
		}
		set
		{
			this._Ordrelinjes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Ordrelinjes(Ordrelinje entity)
	{
		this.SendPropertyChanging();
		entity.Produkt = this;
	}
	
	private void detach_Ordrelinjes(Ordrelinje entity)
	{
		this.SendPropertyChanging();
		entity.Produkt = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AktivitetPåmelding")]
public partial class AktivitetPåmelding : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AktivitetPåmeldingID;
	
	private int _AktivitetID;
	
	private int _BrukerID;
	
	private EntityRef<Bruker> _Bruker;
	
	private EntityRef<Aktivitet> _Aktivitet;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAktivitetPåmeldingIDChanging(int value);
    partial void OnAktivitetPåmeldingIDChanged();
    partial void OnAktivitetIDChanging(int value);
    partial void OnAktivitetIDChanged();
    partial void OnBrukerIDChanging(int value);
    partial void OnBrukerIDChanged();
    #endregion
	
	public AktivitetPåmelding()
	{
		this._Bruker = default(EntityRef<Bruker>);
		this._Aktivitet = default(EntityRef<Aktivitet>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktivitetPåmeldingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int AktivitetPåmeldingID
	{
		get
		{
			return this._AktivitetPåmeldingID;
		}
		set
		{
			if ((this._AktivitetPåmeldingID != value))
			{
				this.OnAktivitetPåmeldingIDChanging(value);
				this.SendPropertyChanging();
				this._AktivitetPåmeldingID = value;
				this.SendPropertyChanged("AktivitetPåmeldingID");
				this.OnAktivitetPåmeldingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktivitetID", DbType="Int NOT NULL")]
	public int AktivitetID
	{
		get
		{
			return this._AktivitetID;
		}
		set
		{
			if ((this._AktivitetID != value))
			{
				if (this._Aktivitet.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnAktivitetIDChanging(value);
				this.SendPropertyChanging();
				this._AktivitetID = value;
				this.SendPropertyChanged("AktivitetID");
				this.OnAktivitetIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrukerID", DbType="Int NOT NULL")]
	public int BrukerID
	{
		get
		{
			return this._BrukerID;
		}
		set
		{
			if ((this._BrukerID != value))
			{
				if (this._Bruker.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnBrukerIDChanging(value);
				this.SendPropertyChanging();
				this._BrukerID = value;
				this.SendPropertyChanged("BrukerID");
				this.OnBrukerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bruker_AktivitetPåmelding", Storage="_Bruker", ThisKey="BrukerID", OtherKey="BrukerID", IsForeignKey=true)]
	public Bruker Bruker
	{
		get
		{
			return this._Bruker.Entity;
		}
		set
		{
			Bruker previousValue = this._Bruker.Entity;
			if (((previousValue != value) 
						|| (this._Bruker.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Bruker.Entity = null;
					previousValue.AktivitetPåmeldings.Remove(this);
				}
				this._Bruker.Entity = value;
				if ((value != null))
				{
					value.AktivitetPåmeldings.Add(this);
					this._BrukerID = value.BrukerID;
				}
				else
				{
					this._BrukerID = default(int);
				}
				this.SendPropertyChanged("Bruker");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aktivitet_AktivitetPåmelding", Storage="_Aktivitet", ThisKey="AktivitetID", OtherKey="AktivitetID", IsForeignKey=true)]
	public Aktivitet Aktivitet
	{
		get
		{
			return this._Aktivitet.Entity;
		}
		set
		{
			Aktivitet previousValue = this._Aktivitet.Entity;
			if (((previousValue != value) 
						|| (this._Aktivitet.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Aktivitet.Entity = null;
					previousValue.AktivitetPåmeldings.Remove(this);
				}
				this._Aktivitet.Entity = value;
				if ((value != null))
				{
					value.AktivitetPåmeldings.Add(this);
					this._AktivitetID = value.AktivitetID;
				}
				else
				{
					this._AktivitetID = default(int);
				}
				this.SendPropertyChanged("Aktivitet");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bruker")]
public partial class Bruker : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _BrukerID;
	
	private string _Brukernavn;
	
	private string _Passord;
	
	private string _Fornavn;
	
	private string _Etternavn;
	
	private int _Mobil;
	
	private EntitySet<AktivitetPåmelding> _AktivitetPåmeldings;
	
	private EntitySet<KursPåmelding> _KursPåmeldings;
	
	private EntitySet<Ordrelinje> _Ordrelinjes;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBrukerIDChanging(int value);
    partial void OnBrukerIDChanged();
    partial void OnBrukernavnChanging(string value);
    partial void OnBrukernavnChanged();
    partial void OnPassordChanging(string value);
    partial void OnPassordChanged();
    partial void OnFornavnChanging(string value);
    partial void OnFornavnChanged();
    partial void OnEtternavnChanging(string value);
    partial void OnEtternavnChanged();
    partial void OnMobilChanging(int value);
    partial void OnMobilChanged();
    #endregion
	
	public Bruker()
	{
		this._AktivitetPåmeldings = new EntitySet<AktivitetPåmelding>(new Action<AktivitetPåmelding>(this.attach_AktivitetPåmeldings), new Action<AktivitetPåmelding>(this.detach_AktivitetPåmeldings));
		this._KursPåmeldings = new EntitySet<KursPåmelding>(new Action<KursPåmelding>(this.attach_KursPåmeldings), new Action<KursPåmelding>(this.detach_KursPåmeldings));
		this._Ordrelinjes = new EntitySet<Ordrelinje>(new Action<Ordrelinje>(this.attach_Ordrelinjes), new Action<Ordrelinje>(this.detach_Ordrelinjes));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrukerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int BrukerID
	{
		get
		{
			return this._BrukerID;
		}
		set
		{
			if ((this._BrukerID != value))
			{
				this.OnBrukerIDChanging(value);
				this.SendPropertyChanging();
				this._BrukerID = value;
				this.SendPropertyChanged("BrukerID");
				this.OnBrukerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brukernavn", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
	public string Brukernavn
	{
		get
		{
			return this._Brukernavn;
		}
		set
		{
			if ((this._Brukernavn != value))
			{
				this.OnBrukernavnChanging(value);
				this.SendPropertyChanging();
				this._Brukernavn = value;
				this.SendPropertyChanged("Brukernavn");
				this.OnBrukernavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passord", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Passord
	{
		get
		{
			return this._Passord;
		}
		set
		{
			if ((this._Passord != value))
			{
				this.OnPassordChanging(value);
				this.SendPropertyChanging();
				this._Passord = value;
				this.SendPropertyChanged("Passord");
				this.OnPassordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fornavn", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string Fornavn
	{
		get
		{
			return this._Fornavn;
		}
		set
		{
			if ((this._Fornavn != value))
			{
				this.OnFornavnChanging(value);
				this.SendPropertyChanging();
				this._Fornavn = value;
				this.SendPropertyChanged("Fornavn");
				this.OnFornavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etternavn", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
	public string Etternavn
	{
		get
		{
			return this._Etternavn;
		}
		set
		{
			if ((this._Etternavn != value))
			{
				this.OnEtternavnChanging(value);
				this.SendPropertyChanging();
				this._Etternavn = value;
				this.SendPropertyChanged("Etternavn");
				this.OnEtternavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobil", DbType="Int NOT NULL")]
	public int Mobil
	{
		get
		{
			return this._Mobil;
		}
		set
		{
			if ((this._Mobil != value))
			{
				this.OnMobilChanging(value);
				this.SendPropertyChanging();
				this._Mobil = value;
				this.SendPropertyChanged("Mobil");
				this.OnMobilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bruker_AktivitetPåmelding", Storage="_AktivitetPåmeldings", ThisKey="BrukerID", OtherKey="BrukerID")]
	public EntitySet<AktivitetPåmelding> AktivitetPåmeldings
	{
		get
		{
			return this._AktivitetPåmeldings;
		}
		set
		{
			this._AktivitetPåmeldings.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bruker_KursPåmelding", Storage="_KursPåmeldings", ThisKey="BrukerID", OtherKey="BrukerID")]
	public EntitySet<KursPåmelding> KursPåmeldings
	{
		get
		{
			return this._KursPåmeldings;
		}
		set
		{
			this._KursPåmeldings.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bruker_Ordrelinje", Storage="_Ordrelinjes", ThisKey="BrukerID", OtherKey="BrukerID")]
	public EntitySet<Ordrelinje> Ordrelinjes
	{
		get
		{
			return this._Ordrelinjes;
		}
		set
		{
			this._Ordrelinjes.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_AktivitetPåmeldings(AktivitetPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Bruker = this;
	}
	
	private void detach_AktivitetPåmeldings(AktivitetPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Bruker = null;
	}
	
	private void attach_KursPåmeldings(KursPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Bruker = this;
	}
	
	private void detach_KursPåmeldings(KursPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Bruker = null;
	}
	
	private void attach_Ordrelinjes(Ordrelinje entity)
	{
		this.SendPropertyChanging();
		entity.Bruker = this;
	}
	
	private void detach_Ordrelinjes(Ordrelinje entity)
	{
		this.SendPropertyChanging();
		entity.Bruker = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Foreleser")]
public partial class Foreleser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ForeleserID;
	
	private string _Fornavn;
	
	private string _Etternavn;
	
	private int _Mobil;
	
	private string _Epost;
	
	private string _Utdanning;
	
	private EntitySet<ForeleserPåmelding> _ForeleserPåmeldings;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnForeleserIDChanging(int value);
    partial void OnForeleserIDChanged();
    partial void OnFornavnChanging(string value);
    partial void OnFornavnChanged();
    partial void OnEtternavnChanging(string value);
    partial void OnEtternavnChanged();
    partial void OnMobilChanging(int value);
    partial void OnMobilChanged();
    partial void OnEpostChanging(string value);
    partial void OnEpostChanged();
    partial void OnUtdanningChanging(string value);
    partial void OnUtdanningChanged();
    #endregion
	
	public Foreleser()
	{
		this._ForeleserPåmeldings = new EntitySet<ForeleserPåmelding>(new Action<ForeleserPåmelding>(this.attach_ForeleserPåmeldings), new Action<ForeleserPåmelding>(this.detach_ForeleserPåmeldings));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeleserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ForeleserID
	{
		get
		{
			return this._ForeleserID;
		}
		set
		{
			if ((this._ForeleserID != value))
			{
				this.OnForeleserIDChanging(value);
				this.SendPropertyChanging();
				this._ForeleserID = value;
				this.SendPropertyChanged("ForeleserID");
				this.OnForeleserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fornavn", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string Fornavn
	{
		get
		{
			return this._Fornavn;
		}
		set
		{
			if ((this._Fornavn != value))
			{
				this.OnFornavnChanging(value);
				this.SendPropertyChanging();
				this._Fornavn = value;
				this.SendPropertyChanged("Fornavn");
				this.OnFornavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etternavn", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string Etternavn
	{
		get
		{
			return this._Etternavn;
		}
		set
		{
			if ((this._Etternavn != value))
			{
				this.OnEtternavnChanging(value);
				this.SendPropertyChanging();
				this._Etternavn = value;
				this.SendPropertyChanged("Etternavn");
				this.OnEtternavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobil", DbType="Int NOT NULL")]
	public int Mobil
	{
		get
		{
			return this._Mobil;
		}
		set
		{
			if ((this._Mobil != value))
			{
				this.OnMobilChanging(value);
				this.SendPropertyChanging();
				this._Mobil = value;
				this.SendPropertyChanged("Mobil");
				this.OnMobilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Epost", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Epost
	{
		get
		{
			return this._Epost;
		}
		set
		{
			if ((this._Epost != value))
			{
				this.OnEpostChanging(value);
				this.SendPropertyChanging();
				this._Epost = value;
				this.SendPropertyChanged("Epost");
				this.OnEpostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Utdanning", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
	public string Utdanning
	{
		get
		{
			return this._Utdanning;
		}
		set
		{
			if ((this._Utdanning != value))
			{
				this.OnUtdanningChanging(value);
				this.SendPropertyChanging();
				this._Utdanning = value;
				this.SendPropertyChanged("Utdanning");
				this.OnUtdanningChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Foreleser_ForeleserPåmelding", Storage="_ForeleserPåmeldings", ThisKey="ForeleserID", OtherKey="ForeleserID")]
	public EntitySet<ForeleserPåmelding> ForeleserPåmeldings
	{
		get
		{
			return this._ForeleserPåmeldings;
		}
		set
		{
			this._ForeleserPåmeldings.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ForeleserPåmeldings(ForeleserPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Foreleser = this;
	}
	
	private void detach_ForeleserPåmeldings(ForeleserPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Foreleser = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ForeleserPåmelding")]
public partial class ForeleserPåmelding : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ForeleserPåmeldingID;
	
	private int _ForeleserID;
	
	private int _KursID;
	
	private EntityRef<Foreleser> _Foreleser;
	
	private EntityRef<Kurs> _Kurs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnForeleserPåmeldingIDChanging(int value);
    partial void OnForeleserPåmeldingIDChanged();
    partial void OnForeleserIDChanging(int value);
    partial void OnForeleserIDChanged();
    partial void OnKursIDChanging(int value);
    partial void OnKursIDChanged();
    #endregion
	
	public ForeleserPåmelding()
	{
		this._Foreleser = default(EntityRef<Foreleser>);
		this._Kurs = default(EntityRef<Kurs>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeleserPåmeldingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ForeleserPåmeldingID
	{
		get
		{
			return this._ForeleserPåmeldingID;
		}
		set
		{
			if ((this._ForeleserPåmeldingID != value))
			{
				this.OnForeleserPåmeldingIDChanging(value);
				this.SendPropertyChanging();
				this._ForeleserPåmeldingID = value;
				this.SendPropertyChanged("ForeleserPåmeldingID");
				this.OnForeleserPåmeldingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeleserID", DbType="Int NOT NULL")]
	public int ForeleserID
	{
		get
		{
			return this._ForeleserID;
		}
		set
		{
			if ((this._ForeleserID != value))
			{
				if (this._Foreleser.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnForeleserIDChanging(value);
				this.SendPropertyChanging();
				this._ForeleserID = value;
				this.SendPropertyChanged("ForeleserID");
				this.OnForeleserIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KursID", DbType="Int NOT NULL")]
	public int KursID
	{
		get
		{
			return this._KursID;
		}
		set
		{
			if ((this._KursID != value))
			{
				if (this._Kurs.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnKursIDChanging(value);
				this.SendPropertyChanging();
				this._KursID = value;
				this.SendPropertyChanged("KursID");
				this.OnKursIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Foreleser_ForeleserPåmelding", Storage="_Foreleser", ThisKey="ForeleserID", OtherKey="ForeleserID", IsForeignKey=true)]
	public Foreleser Foreleser
	{
		get
		{
			return this._Foreleser.Entity;
		}
		set
		{
			Foreleser previousValue = this._Foreleser.Entity;
			if (((previousValue != value) 
						|| (this._Foreleser.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Foreleser.Entity = null;
					previousValue.ForeleserPåmeldings.Remove(this);
				}
				this._Foreleser.Entity = value;
				if ((value != null))
				{
					value.ForeleserPåmeldings.Add(this);
					this._ForeleserID = value.ForeleserID;
				}
				else
				{
					this._ForeleserID = default(int);
				}
				this.SendPropertyChanged("Foreleser");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurs_ForeleserPåmelding", Storage="_Kurs", ThisKey="KursID", OtherKey="KursID", IsForeignKey=true)]
	public Kurs Kurs
	{
		get
		{
			return this._Kurs.Entity;
		}
		set
		{
			Kurs previousValue = this._Kurs.Entity;
			if (((previousValue != value) 
						|| (this._Kurs.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Kurs.Entity = null;
					previousValue.ForeleserPåmeldings.Remove(this);
				}
				this._Kurs.Entity = value;
				if ((value != null))
				{
					value.ForeleserPåmeldings.Add(this);
					this._KursID = value.KursID;
				}
				else
				{
					this._KursID = default(int);
				}
				this.SendPropertyChanged("Kurs");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kurs")]
public partial class Kurs : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _KursID;
	
	private string _Kursnavn;
	
	private string _Beskrivelse;
	
	private System.DateTime _Påmeldingsfrist;
	
	private System.DateTime _Startdato;
	
	private System.DateTime _Sluttdato;
	
	private string _Målgruppe;
	
	private string _Tilleggsinformasjon;
	
	private int _MaxAntallDeltakere;
	
	private string _KursAnsvarlig;
	
	private string _Samarbeidspartnere;
	
	private EntitySet<ForeleserPåmelding> _ForeleserPåmeldings;
	
	private EntitySet<KursPåmelding> _KursPåmeldings;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKursIDChanging(int value);
    partial void OnKursIDChanged();
    partial void OnKursnavnChanging(string value);
    partial void OnKursnavnChanged();
    partial void OnBeskrivelseChanging(string value);
    partial void OnBeskrivelseChanged();
    partial void OnPåmeldingsfristChanging(System.DateTime value);
    partial void OnPåmeldingsfristChanged();
    partial void OnStartdatoChanging(System.DateTime value);
    partial void OnStartdatoChanged();
    partial void OnSluttdatoChanging(System.DateTime value);
    partial void OnSluttdatoChanged();
    partial void OnMålgruppeChanging(string value);
    partial void OnMålgruppeChanged();
    partial void OnTilleggsinformasjonChanging(string value);
    partial void OnTilleggsinformasjonChanged();
    partial void OnMaxAntallDeltakereChanging(int value);
    partial void OnMaxAntallDeltakereChanged();
    partial void OnKursAnsvarligChanging(string value);
    partial void OnKursAnsvarligChanged();
    partial void OnSamarbeidspartnereChanging(string value);
    partial void OnSamarbeidspartnereChanged();
    #endregion
	
	public Kurs()
	{
		this._ForeleserPåmeldings = new EntitySet<ForeleserPåmelding>(new Action<ForeleserPåmelding>(this.attach_ForeleserPåmeldings), new Action<ForeleserPåmelding>(this.detach_ForeleserPåmeldings));
		this._KursPåmeldings = new EntitySet<KursPåmelding>(new Action<KursPåmelding>(this.attach_KursPåmeldings), new Action<KursPåmelding>(this.detach_KursPåmeldings));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KursID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int KursID
	{
		get
		{
			return this._KursID;
		}
		set
		{
			if ((this._KursID != value))
			{
				this.OnKursIDChanging(value);
				this.SendPropertyChanging();
				this._KursID = value;
				this.SendPropertyChanged("KursID");
				this.OnKursIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kursnavn", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
	public string Kursnavn
	{
		get
		{
			return this._Kursnavn;
		}
		set
		{
			if ((this._Kursnavn != value))
			{
				this.OnKursnavnChanging(value);
				this.SendPropertyChanging();
				this._Kursnavn = value;
				this.SendPropertyChanged("Kursnavn");
				this.OnKursnavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beskrivelse", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Beskrivelse
	{
		get
		{
			return this._Beskrivelse;
		}
		set
		{
			if ((this._Beskrivelse != value))
			{
				this.OnBeskrivelseChanging(value);
				this.SendPropertyChanging();
				this._Beskrivelse = value;
				this.SendPropertyChanged("Beskrivelse");
				this.OnBeskrivelseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Påmeldingsfrist", DbType="DateTime NOT NULL")]
	public System.DateTime Påmeldingsfrist
	{
		get
		{
			return this._Påmeldingsfrist;
		}
		set
		{
			if ((this._Påmeldingsfrist != value))
			{
				this.OnPåmeldingsfristChanging(value);
				this.SendPropertyChanging();
				this._Påmeldingsfrist = value;
				this.SendPropertyChanged("Påmeldingsfrist");
				this.OnPåmeldingsfristChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Startdato", DbType="DateTime NOT NULL")]
	public System.DateTime Startdato
	{
		get
		{
			return this._Startdato;
		}
		set
		{
			if ((this._Startdato != value))
			{
				this.OnStartdatoChanging(value);
				this.SendPropertyChanging();
				this._Startdato = value;
				this.SendPropertyChanged("Startdato");
				this.OnStartdatoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sluttdato", DbType="DateTime NOT NULL")]
	public System.DateTime Sluttdato
	{
		get
		{
			return this._Sluttdato;
		}
		set
		{
			if ((this._Sluttdato != value))
			{
				this.OnSluttdatoChanging(value);
				this.SendPropertyChanging();
				this._Sluttdato = value;
				this.SendPropertyChanged("Sluttdato");
				this.OnSluttdatoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Målgruppe", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Målgruppe
	{
		get
		{
			return this._Målgruppe;
		}
		set
		{
			if ((this._Målgruppe != value))
			{
				this.OnMålgruppeChanging(value);
				this.SendPropertyChanging();
				this._Målgruppe = value;
				this.SendPropertyChanged("Målgruppe");
				this.OnMålgruppeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tilleggsinformasjon", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string Tilleggsinformasjon
	{
		get
		{
			return this._Tilleggsinformasjon;
		}
		set
		{
			if ((this._Tilleggsinformasjon != value))
			{
				this.OnTilleggsinformasjonChanging(value);
				this.SendPropertyChanging();
				this._Tilleggsinformasjon = value;
				this.SendPropertyChanged("Tilleggsinformasjon");
				this.OnTilleggsinformasjonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxAntallDeltakere", DbType="Int NOT NULL")]
	public int MaxAntallDeltakere
	{
		get
		{
			return this._MaxAntallDeltakere;
		}
		set
		{
			if ((this._MaxAntallDeltakere != value))
			{
				this.OnMaxAntallDeltakereChanging(value);
				this.SendPropertyChanging();
				this._MaxAntallDeltakere = value;
				this.SendPropertyChanged("MaxAntallDeltakere");
				this.OnMaxAntallDeltakereChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KursAnsvarlig", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string KursAnsvarlig
	{
		get
		{
			return this._KursAnsvarlig;
		}
		set
		{
			if ((this._KursAnsvarlig != value))
			{
				this.OnKursAnsvarligChanging(value);
				this.SendPropertyChanging();
				this._KursAnsvarlig = value;
				this.SendPropertyChanged("KursAnsvarlig");
				this.OnKursAnsvarligChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Samarbeidspartnere", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Samarbeidspartnere
	{
		get
		{
			return this._Samarbeidspartnere;
		}
		set
		{
			if ((this._Samarbeidspartnere != value))
			{
				this.OnSamarbeidspartnereChanging(value);
				this.SendPropertyChanging();
				this._Samarbeidspartnere = value;
				this.SendPropertyChanged("Samarbeidspartnere");
				this.OnSamarbeidspartnereChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurs_ForeleserPåmelding", Storage="_ForeleserPåmeldings", ThisKey="KursID", OtherKey="KursID")]
	public EntitySet<ForeleserPåmelding> ForeleserPåmeldings
	{
		get
		{
			return this._ForeleserPåmeldings;
		}
		set
		{
			this._ForeleserPåmeldings.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurs_KursPåmelding", Storage="_KursPåmeldings", ThisKey="KursID", OtherKey="KursID")]
	public EntitySet<KursPåmelding> KursPåmeldings
	{
		get
		{
			return this._KursPåmeldings;
		}
		set
		{
			this._KursPåmeldings.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ForeleserPåmeldings(ForeleserPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Kurs = this;
	}
	
	private void detach_ForeleserPåmeldings(ForeleserPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Kurs = null;
	}
	
	private void attach_KursPåmeldings(KursPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Kurs = this;
	}
	
	private void detach_KursPåmeldings(KursPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Kurs = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KursPåmelding")]
public partial class KursPåmelding : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _KursPåmeldingID;
	
	private int _KursID;
	
	private int _BrukerID;
	
	private EntityRef<Bruker> _Bruker;
	
	private EntityRef<Kurs> _Kurs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKursPåmeldingIDChanging(int value);
    partial void OnKursPåmeldingIDChanged();
    partial void OnKursIDChanging(int value);
    partial void OnKursIDChanged();
    partial void OnBrukerIDChanging(int value);
    partial void OnBrukerIDChanged();
    #endregion
	
	public KursPåmelding()
	{
		this._Bruker = default(EntityRef<Bruker>);
		this._Kurs = default(EntityRef<Kurs>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KursPåmeldingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int KursPåmeldingID
	{
		get
		{
			return this._KursPåmeldingID;
		}
		set
		{
			if ((this._KursPåmeldingID != value))
			{
				this.OnKursPåmeldingIDChanging(value);
				this.SendPropertyChanging();
				this._KursPåmeldingID = value;
				this.SendPropertyChanged("KursPåmeldingID");
				this.OnKursPåmeldingIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KursID", DbType="Int NOT NULL")]
	public int KursID
	{
		get
		{
			return this._KursID;
		}
		set
		{
			if ((this._KursID != value))
			{
				if (this._Kurs.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnKursIDChanging(value);
				this.SendPropertyChanging();
				this._KursID = value;
				this.SendPropertyChanged("KursID");
				this.OnKursIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrukerID", DbType="Int NOT NULL")]
	public int BrukerID
	{
		get
		{
			return this._BrukerID;
		}
		set
		{
			if ((this._BrukerID != value))
			{
				if (this._Bruker.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnBrukerIDChanging(value);
				this.SendPropertyChanging();
				this._BrukerID = value;
				this.SendPropertyChanged("BrukerID");
				this.OnBrukerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bruker_KursPåmelding", Storage="_Bruker", ThisKey="BrukerID", OtherKey="BrukerID", IsForeignKey=true)]
	public Bruker Bruker
	{
		get
		{
			return this._Bruker.Entity;
		}
		set
		{
			Bruker previousValue = this._Bruker.Entity;
			if (((previousValue != value) 
						|| (this._Bruker.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Bruker.Entity = null;
					previousValue.KursPåmeldings.Remove(this);
				}
				this._Bruker.Entity = value;
				if ((value != null))
				{
					value.KursPåmeldings.Add(this);
					this._BrukerID = value.BrukerID;
				}
				else
				{
					this._BrukerID = default(int);
				}
				this.SendPropertyChanged("Bruker");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kurs_KursPåmelding", Storage="_Kurs", ThisKey="KursID", OtherKey="KursID", IsForeignKey=true)]
	public Kurs Kurs
	{
		get
		{
			return this._Kurs.Entity;
		}
		set
		{
			Kurs previousValue = this._Kurs.Entity;
			if (((previousValue != value) 
						|| (this._Kurs.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Kurs.Entity = null;
					previousValue.KursPåmeldings.Remove(this);
				}
				this._Kurs.Entity = value;
				if ((value != null))
				{
					value.KursPåmeldings.Add(this);
					this._KursID = value.KursID;
				}
				else
				{
					this._KursID = default(int);
				}
				this.SendPropertyChanged("Kurs");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bilder")]
public partial class Bilder : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _BildeID;
	
	private string _Bildenavn;
	
	private string _Path;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBildeIDChanging(int value);
    partial void OnBildeIDChanged();
    partial void OnBildenavnChanging(string value);
    partial void OnBildenavnChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    #endregion
	
	public Bilder()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BildeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int BildeID
	{
		get
		{
			return this._BildeID;
		}
		set
		{
			if ((this._BildeID != value))
			{
				this.OnBildeIDChanging(value);
				this.SendPropertyChanging();
				this._BildeID = value;
				this.SendPropertyChanged("BildeID");
				this.OnBildeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bildenavn", DbType="NVarChar(MAX)")]
	public string Bildenavn
	{
		get
		{
			return this._Bildenavn;
		}
		set
		{
			if ((this._Bildenavn != value))
			{
				this.OnBildenavnChanging(value);
				this.SendPropertyChanging();
				this._Bildenavn = value;
				this.SendPropertyChanged("Bildenavn");
				this.OnBildenavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="NVarChar(50)")]
	public string Path
	{
		get
		{
			return this._Path;
		}
		set
		{
			if ((this._Path != value))
			{
				this.OnPathChanging(value);
				this.SendPropertyChanging();
				this._Path = value;
				this.SendPropertyChanged("Path");
				this.OnPathChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ordrelinje")]
public partial class Ordrelinje : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _OrdrelinjeID;
	
	private int _ProduktID;
	
	private int _BrukerID;
	
	private string _Leveringsadresse;
	
	private string _Postnummer;
	
	private EntityRef<Bruker> _Bruker;
	
	private EntityRef<Produkt> _Produkt;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrdrelinjeIDChanging(int value);
    partial void OnOrdrelinjeIDChanged();
    partial void OnProduktIDChanging(int value);
    partial void OnProduktIDChanged();
    partial void OnBrukerIDChanging(int value);
    partial void OnBrukerIDChanged();
    partial void OnLeveringsadresseChanging(string value);
    partial void OnLeveringsadresseChanged();
    partial void OnPostnummerChanging(string value);
    partial void OnPostnummerChanged();
    #endregion
	
	public Ordrelinje()
	{
		this._Bruker = default(EntityRef<Bruker>);
		this._Produkt = default(EntityRef<Produkt>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrdrelinjeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int OrdrelinjeID
	{
		get
		{
			return this._OrdrelinjeID;
		}
		set
		{
			if ((this._OrdrelinjeID != value))
			{
				this.OnOrdrelinjeIDChanging(value);
				this.SendPropertyChanging();
				this._OrdrelinjeID = value;
				this.SendPropertyChanged("OrdrelinjeID");
				this.OnOrdrelinjeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProduktID", DbType="Int NOT NULL")]
	public int ProduktID
	{
		get
		{
			return this._ProduktID;
		}
		set
		{
			if ((this._ProduktID != value))
			{
				if (this._Produkt.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnProduktIDChanging(value);
				this.SendPropertyChanging();
				this._ProduktID = value;
				this.SendPropertyChanged("ProduktID");
				this.OnProduktIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrukerID", DbType="Int NOT NULL")]
	public int BrukerID
	{
		get
		{
			return this._BrukerID;
		}
		set
		{
			if ((this._BrukerID != value))
			{
				if (this._Bruker.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnBrukerIDChanging(value);
				this.SendPropertyChanging();
				this._BrukerID = value;
				this.SendPropertyChanged("BrukerID");
				this.OnBrukerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leveringsadresse", DbType="NVarChar(100)")]
	public string Leveringsadresse
	{
		get
		{
			return this._Leveringsadresse;
		}
		set
		{
			if ((this._Leveringsadresse != value))
			{
				this.OnLeveringsadresseChanging(value);
				this.SendPropertyChanging();
				this._Leveringsadresse = value;
				this.SendPropertyChanged("Leveringsadresse");
				this.OnLeveringsadresseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postnummer", DbType="NVarChar(50)")]
	public string Postnummer
	{
		get
		{
			return this._Postnummer;
		}
		set
		{
			if ((this._Postnummer != value))
			{
				this.OnPostnummerChanging(value);
				this.SendPropertyChanging();
				this._Postnummer = value;
				this.SendPropertyChanged("Postnummer");
				this.OnPostnummerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bruker_Ordrelinje", Storage="_Bruker", ThisKey="BrukerID", OtherKey="BrukerID", IsForeignKey=true)]
	public Bruker Bruker
	{
		get
		{
			return this._Bruker.Entity;
		}
		set
		{
			Bruker previousValue = this._Bruker.Entity;
			if (((previousValue != value) 
						|| (this._Bruker.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Bruker.Entity = null;
					previousValue.Ordrelinjes.Remove(this);
				}
				this._Bruker.Entity = value;
				if ((value != null))
				{
					value.Ordrelinjes.Add(this);
					this._BrukerID = value.BrukerID;
				}
				else
				{
					this._BrukerID = default(int);
				}
				this.SendPropertyChanged("Bruker");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produkt_Ordrelinje", Storage="_Produkt", ThisKey="ProduktID", OtherKey="ProduktID", IsForeignKey=true)]
	public Produkt Produkt
	{
		get
		{
			return this._Produkt.Entity;
		}
		set
		{
			Produkt previousValue = this._Produkt.Entity;
			if (((previousValue != value) 
						|| (this._Produkt.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Produkt.Entity = null;
					previousValue.Ordrelinjes.Remove(this);
				}
				this._Produkt.Entity = value;
				if ((value != null))
				{
					value.Ordrelinjes.Add(this);
					this._ProduktID = value.ProduktID;
				}
				else
				{
					this._ProduktID = default(int);
				}
				this.SendPropertyChanged("Produkt");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nyhet")]
public partial class Nyhet : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _NyhetsID;
	
	private string _Tittel;
	
	private string _Ingress;
	
	private string _Brødtekst;
	
	private string _Bildetittel;
	
	private string _Dato;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNyhetsIDChanging(int value);
    partial void OnNyhetsIDChanged();
    partial void OnTittelChanging(string value);
    partial void OnTittelChanged();
    partial void OnIngressChanging(string value);
    partial void OnIngressChanged();
    partial void OnBrødtekstChanging(string value);
    partial void OnBrødtekstChanged();
    partial void OnBildetittelChanging(string value);
    partial void OnBildetittelChanged();
    partial void OnDatoChanging(string value);
    partial void OnDatoChanged();
    #endregion
	
	public Nyhet()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NyhetsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int NyhetsID
	{
		get
		{
			return this._NyhetsID;
		}
		set
		{
			if ((this._NyhetsID != value))
			{
				this.OnNyhetsIDChanging(value);
				this.SendPropertyChanging();
				this._NyhetsID = value;
				this.SendPropertyChanged("NyhetsID");
				this.OnNyhetsIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tittel", DbType="NVarChar(80)")]
	public string Tittel
	{
		get
		{
			return this._Tittel;
		}
		set
		{
			if ((this._Tittel != value))
			{
				this.OnTittelChanging(value);
				this.SendPropertyChanging();
				this._Tittel = value;
				this.SendPropertyChanged("Tittel");
				this.OnTittelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingress", DbType="NVarChar(1000)")]
	public string Ingress
	{
		get
		{
			return this._Ingress;
		}
		set
		{
			if ((this._Ingress != value))
			{
				this.OnIngressChanging(value);
				this.SendPropertyChanging();
				this._Ingress = value;
				this.SendPropertyChanged("Ingress");
				this.OnIngressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Brødtekst", DbType="NVarChar(4000)")]
	public string Brødtekst
	{
		get
		{
			return this._Brødtekst;
		}
		set
		{
			if ((this._Brødtekst != value))
			{
				this.OnBrødtekstChanging(value);
				this.SendPropertyChanging();
				this._Brødtekst = value;
				this.SendPropertyChanged("Brødtekst");
				this.OnBrødtekstChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bildetittel", DbType="NVarChar(50)")]
	public string Bildetittel
	{
		get
		{
			return this._Bildetittel;
		}
		set
		{
			if ((this._Bildetittel != value))
			{
				this.OnBildetittelChanging(value);
				this.SendPropertyChanging();
				this._Bildetittel = value;
				this.SendPropertyChanged("Bildetittel");
				this.OnBildetittelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dato", DbType="NVarChar(50)")]
	public string Dato
	{
		get
		{
			return this._Dato;
		}
		set
		{
			if ((this._Dato != value))
			{
				this.OnDatoChanging(value);
				this.SendPropertyChanging();
				this._Dato = value;
				this.SendPropertyChanged("Dato");
				this.OnDatoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aktivitet")]
public partial class Aktivitet : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _AktivitetID;
	
	private string _AktivitetNavn;
	
	private string _Beskrivelse;
	
	private System.DateTime _Startdato;
	
	private System.DateTime _Sluttdato;
	
	private string _StartTidspunkt;
	
	private string _SluttTidspunkt;
	
	private EntitySet<AktivitetPåmelding> _AktivitetPåmeldings;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAktivitetIDChanging(int value);
    partial void OnAktivitetIDChanged();
    partial void OnAktivitetNavnChanging(string value);
    partial void OnAktivitetNavnChanged();
    partial void OnBeskrivelseChanging(string value);
    partial void OnBeskrivelseChanged();
    partial void OnStartdatoChanging(System.DateTime value);
    partial void OnStartdatoChanged();
    partial void OnSluttdatoChanging(System.DateTime value);
    partial void OnSluttdatoChanged();
    partial void OnStartTidspunktChanging(string value);
    partial void OnStartTidspunktChanged();
    partial void OnSluttTidspunktChanging(string value);
    partial void OnSluttTidspunktChanged();
    #endregion
	
	public Aktivitet()
	{
		this._AktivitetPåmeldings = new EntitySet<AktivitetPåmelding>(new Action<AktivitetPåmelding>(this.attach_AktivitetPåmeldings), new Action<AktivitetPåmelding>(this.detach_AktivitetPåmeldings));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktivitetID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int AktivitetID
	{
		get
		{
			return this._AktivitetID;
		}
		set
		{
			if ((this._AktivitetID != value))
			{
				this.OnAktivitetIDChanging(value);
				this.SendPropertyChanging();
				this._AktivitetID = value;
				this.SendPropertyChanged("AktivitetID");
				this.OnAktivitetIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AktivitetNavn", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string AktivitetNavn
	{
		get
		{
			return this._AktivitetNavn;
		}
		set
		{
			if ((this._AktivitetNavn != value))
			{
				this.OnAktivitetNavnChanging(value);
				this.SendPropertyChanging();
				this._AktivitetNavn = value;
				this.SendPropertyChanged("AktivitetNavn");
				this.OnAktivitetNavnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beskrivelse", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Beskrivelse
	{
		get
		{
			return this._Beskrivelse;
		}
		set
		{
			if ((this._Beskrivelse != value))
			{
				this.OnBeskrivelseChanging(value);
				this.SendPropertyChanging();
				this._Beskrivelse = value;
				this.SendPropertyChanged("Beskrivelse");
				this.OnBeskrivelseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Startdato", DbType="DateTime NOT NULL")]
	public System.DateTime Startdato
	{
		get
		{
			return this._Startdato;
		}
		set
		{
			if ((this._Startdato != value))
			{
				this.OnStartdatoChanging(value);
				this.SendPropertyChanging();
				this._Startdato = value;
				this.SendPropertyChanged("Startdato");
				this.OnStartdatoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sluttdato", DbType="DateTime NOT NULL")]
	public System.DateTime Sluttdato
	{
		get
		{
			return this._Sluttdato;
		}
		set
		{
			if ((this._Sluttdato != value))
			{
				this.OnSluttdatoChanging(value);
				this.SendPropertyChanging();
				this._Sluttdato = value;
				this.SendPropertyChanged("Sluttdato");
				this.OnSluttdatoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTidspunkt", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string StartTidspunkt
	{
		get
		{
			return this._StartTidspunkt;
		}
		set
		{
			if ((this._StartTidspunkt != value))
			{
				this.OnStartTidspunktChanging(value);
				this.SendPropertyChanging();
				this._StartTidspunkt = value;
				this.SendPropertyChanged("StartTidspunkt");
				this.OnStartTidspunktChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SluttTidspunkt", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string SluttTidspunkt
	{
		get
		{
			return this._SluttTidspunkt;
		}
		set
		{
			if ((this._SluttTidspunkt != value))
			{
				this.OnSluttTidspunktChanging(value);
				this.SendPropertyChanging();
				this._SluttTidspunkt = value;
				this.SendPropertyChanged("SluttTidspunkt");
				this.OnSluttTidspunktChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Aktivitet_AktivitetPåmelding", Storage="_AktivitetPåmeldings", ThisKey="AktivitetID", OtherKey="AktivitetID")]
	public EntitySet<AktivitetPåmelding> AktivitetPåmeldings
	{
		get
		{
			return this._AktivitetPåmeldings;
		}
		set
		{
			this._AktivitetPåmeldings.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_AktivitetPåmeldings(AktivitetPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Aktivitet = this;
	}
	
	private void detach_AktivitetPåmeldings(AktivitetPåmelding entity)
	{
		this.SendPropertyChanging();
		entity.Aktivitet = null;
	}
}
#pragma warning restore 1591
